# Generated by Django 5.2.1 on 2025-05-18 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothingitem',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
